CREATE TABLE egress(
    seq BIGINT NOT NULL AUTO_INCREMENT COMMENT '流水編號'
    , index egress_seq_idx(seq)
    , formcode CHAR(10) NOT NULL COMMENT '表單編號'
    , PRIMARY KEY(formcode)
    , formstate TINYINT NOT NULL DEFAULT 15 COMMENT '表單狀況'
    , creator VARCHAR(60) NOT NULL DEFAULT 'SYSTEM' COMMENT '建立者'
    , creatdate DATETIME NOT NULL DEFAULT current_timestamp() COMMENT '建立日期'
    , modifier VARCHAR(60) NOT NULL DEFAULT 'SYSTEM' COMMENT '修改者'
    , modifydate DATETIME NOT NULL DEFAULT current_timestamp() COMMENT '修改日期'
    , deptspk CHAR(10) NOT NULL COMMENT '機構檔主鍵'
    , cmpcode VARCHAR(20) NOT NULL COMMENT '機構代碼'
    , cmpapl VARCHAR(300) NOT NULL COMMENT '機構名稱'
    , index egress_cmpapl_idx(cmpapl)
    , empformcode CHAR(10) NOT NULL COMMENT '員工檔主鍵'
    , empapl VARCHAR(20) NOT NULL COMMENT '員工檔員工姓名'
    , empcode VARCHAR(20) NOT NULL COMMENT '員工檔員工編號'
    , year INT NOT NULL COMMENT '年度(西元年)'
    , cls VARCHAR(60) NOT NULL DEFAULT '外出' COMMENT '類別(外出_加班)'
    , egrersn VARCHAR(600) NOT NULL COMMENT '外出事由'
    , begindate DATETIME NOT NULL COMMENT '外出啟始日'
    , enddate DATETIME NOT NULL COMMENT '外出結束日'
    , applydate DATETIME NOT NULL DEFAULT current_timestamp() COMMENT '外出者簽核時間'
    , frmformcode CHAR(10) NOT NULL COMMENT '表單審核狀態唯一識別碼'
    , frmlistapl VARCHAR(300) NOT NULL COMMENT '表單審核狀態名稱'
    , mngrformcode CHAR(10) NULL COMMENT '單位主管唯一識別碼'
    , mngrapl VARCHAR(20) NULL COMMENT '單位主管姓名'
    , mngrcode VARCHAR(20) NULL COMMENT '單位主管編號'
    , mngrvrfdate DATETIME NULL COMMENT '單位主管簽核日期'
    , cifformcode CHAR(10) NULL COMMENT '主任唯一識別碼'
    , cifapl VARCHAR(20) NULL COMMENT '主任姓名'
    , cifcode VARCHAR(20) NULL COMMENT '主任編號'
    , cifvrfdate DATETIME NULL COMMENT '主任簽核日期'
) COMMENT '外出檔', AUTO_INCREMENT=1;