CREATE TABLE holidays(
    seq BIGINT NOT NULL AUTO_INCREMENT COMMENT '流水編號'
    , index hlds_seq_idx(seq)
    , formcode CHAR(10) NOT NULL COMMENT '表單編號'
    , PRIMARY KEY(formcode)
    , formstate TINYINT NOT NULL DEFAULT 15 COMMENT '表單狀況'
    , creator VARCHAR(20) NOT NULL DEFAULT 'SYSTEM' COMMENT '建立者'
    , creatdate DATETIME NOT NULL DEFAULT current_timestamp() COMMENT '建立日期'
    , modifier VARCHAR(20) NOT NULL DEFAULT 'SYSTEM' COMMENT '修改者'
    , modifydate DATETIME NOT NULL DEFAULT current_timestamp() COMMENT '修改日期'
    , empformcode CHAR(10) NOT NULL COMMENT '員工檔唯一識別碼'
    , empapl VARCHAR(20) NOT NULL COMMENT '員工姓名'
    , empcode VARCHAR(20) NOT NULL COMMENT '員工編號'
    , takeofcdate DATE NOT NULL COMMENT '到職日'
    , amlhrs DOUBLE NOT NULL DEFAULT 0 COMMENT '過去未休假的累積時數'
    , curhrs DOUBLE NOT NULL DEFAULT 0 COMMENT '目前可特休時數'
    , year INT NOT NULL COMMENT '年度'
    , hldformcode CHAR(10) NOT NULL COMMENT '請假別唯一識別碼'
    , hldclsapl VARCHAR(300) NOT NULL COMMENT '請假別名稱'
    , hldrsn VARCHAR(600) NOT NULL COMMENT '請假事由'
    , begindate DATETIME NOT NULL COMMENT '請假啟始日'
    , enddate DATETIME NOT NULL COMMENT '請假結束日'
    , hldsdays DOUBLE NOT NULL DEFAULT 0 COMMENT '請假天數'
    , hldshrs DOUBLE NOT NULL DEFAULT 0 COMMENT '請假時數'
    , applydate DATETIME NOT NULL DEFAULT current_timestamp() COMMENT '請假者簽核時間'
    , frmformcode CHAR(10) NOT NULL COMMENT '表單審核狀態唯一識別碼'
    , frmlistapl VARCHAR(300) NOT NULL COMMENT '表單審核狀態名稱'
    , pryformcode CHAR(10) NULL COMMENT '職務代理人唯一識別碼'
    , pryapl VARCHAR(20) NULL COMMENT '職務代理人姓名'
    , prycode VARCHAR(20) NULL COMMENT '職務代理人編號'
    , pryvrfdate DATETIME NULL COMMENT '職務代理人簽核日期'
    , mngrformcode CHAR(10) NULL COMMENT '單位主管唯一識別碼'
    , mngrapl VARCHAR(20) NULL COMMENT '單位主管姓名'
    , mngrcode VARCHAR(20) NULL COMMENT '單位主管編號'
    , mngrvrfdate DATETIME NULL COMMENT '單位主管簽核日期'
    , hrformcode CHAR(10) NULL COMMENT '人事主管唯一識別碼'
    , hrapl VARCHAR(20) NULL COMMENT '人事主管姓名'
    , hrcode VARCHAR(20) NULL COMMENT '人事主管編號'
    , hrvrfdate DATETIME NULL COMMENT '人事主管簽核日期'
    , cifformcode CHAR(10) NULL COMMENT '主任唯一識別碼'
    , cifapl VARCHAR(20) NULL COMMENT '主任姓名'
    , cifcode VARCHAR(20) NULL COMMENT '主任編號'
    , cifvrfdate DATETIME NULL COMMENT '主任簽核日期'
) COMMENT '請假檔', AUTO_INCREMENT=1;
